//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkin_Custommer
    {
        public int id { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CheckInID { get; set; }
        public Nullable<bool> roomMaster { get; set; }
    
        public virtual CheckIn CheckIn { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
