//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Groups = new HashSet<Group>();
            this.Revervations = new HashSet<Revervation>();
            this.CheckIns = new HashSet<CheckIn>();
            this.checkin_Custommer = new HashSet<checkin_Custommer>();
        }
    
        public int CustomerID { get; set; }
        public string IDCard { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string Company { get; set; }
    
        public virtual Nationality Nationality { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Revervation> Revervations { get; set; }
        public virtual ICollection<CheckIn> CheckIns { get; set; }
        public virtual ICollection<checkin_Custommer> checkin_Custommer { get; set; }
    }
}
