//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revervation
    {
        public int ReservationID { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PeopleNumber { get; set; }
        public string ListRoom { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public string Requests { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RevervationRoom RevervationRoom { get; set; }
    }
}
