//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public RoomType()
        {
            this.Equipments = new HashSet<Equipment>();
            this.RevervationRooms = new HashSet<RevervationRoom>();
            this.Rooms = new HashSet<Room>();
        }
    
        public string RoomTypeID { get; set; }
        public string RoomTypeName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Depcriptions { get; set; }
    
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual ICollection<RevervationRoom> RevervationRooms { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
