//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseAmenity
    {
        public string AmentityID { get; set; }
        public Nullable<int> CheckInID { get; set; }
        public Nullable<int> NumberUse { get; set; }
    
        public virtual Amenity Amenity { get; set; }
    }
}
