//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedServiceCode
    {
        public UsedServiceCode()
        {
            this.UsedServices = new HashSet<UsedService>();
        }
    
        public int UsedServiceCodeID { get; set; }
        public Nullable<int> CheckInID { get; set; }
        public string GuestNameUsed { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<System.DateTime> DateUsed { get; set; }
        public string ServiceComment { get; set; }
        public Nullable<bool> StatusUsed { get; set; }
        public Nullable<decimal> Payed { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual CheckIn CheckIn { get; set; }
        public virtual ICollection<UsedService> UsedServices { get; set; }
    }
}
