//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Amenity
    {
        public string AmenityID { get; set; }
        [Display(Name = "Tên thiết bị")]
        public string AmenityName { get; set; }
        [Display(Name = "Giá")]
        public Nullable<decimal> Price { get; set; }
        [Display(Name = "Mô tả")]
        public string Description { get; set; }
        [Display(Name = "Đơn vị")]
        public string AmenityUnit { get; set; }

        public virtual RoomType_Amenity RoomType_Amenity { get; set; }
    }
}
