//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGCOMP
    {
        public string CompanyName { get; set; }
        public string CompanyAdd { get; set; }
        public string TaxCode { get; set; }
        public string AccountNo { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Fax { get; set; }
        public Nullable<int> FloorNo { get; set; }
        public Nullable<int> PositionNo { get; set; }
    }
}
