//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public Customer()
        {
            this.checkin_Custommer = new HashSet<checkin_Custommer>();
            this.Revervations = new HashSet<Revervation>();
        }

        [Display(Name = "Mã khách hàng")]
        public int CustomerID { get; set; }
        [Display(Name = "Số CMND/Hộ chiếu")]
        public string IDCard { get; set; }
        [Display(Name = "Họ và tên")]
        public string Name { get; set; }
        [Display(Name = "Số điện thoại")]
        public string Phone { get; set; }
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Mail { get; set; }
        [Display(Name = "Địa chỉ")]
        public string Address { get; set; }
        [Display(Name = "Giới tính")]
        public Nullable<bool> Sex { get; set; }
        [Display(Name = "Quốc gia")]
        public Nullable<int> NationalityID { get; set; }
        [Display(Name = "Công ty")]
        public string Company { get; set; }

        public virtual ICollection<checkin_Custommer> checkin_Custommer { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual ICollection<Revervation> Revervations { get; set; }
    }
}
