//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        [Display(Name = "Ngày trả phòng")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> CheckInID { get; set; }
        [Display(Name = "Tổng tiền")]
        public Nullable<decimal> Total { get; set; }

        public virtual CheckIn CheckIn { get; set; }
    }
}
