//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Revervation
    {

        public Revervation()
        {
            this.ReservationsRooms = new HashSet<ReservationsRoom>();
        }

        public int ReservationID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        [Display(Name="Số người")]
        [Required(ErrorMessage="Không được để trống")]
        [Range(1,1000,ErrorMessage="Số người phải là 0 - 1000")]
        public Nullable<int> PeopleNumber { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Ngày nhận phòng")]
        [Required(ErrorMessage = "Không được để trống")]
        public Nullable<System.DateTime> DateIn { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Ngày trả phòng")]
        [Required(ErrorMessage = "Không được để trống")]
        public Nullable<System.DateTime> DateOut { get; set; }
        [Display(Name = "Yêu cầu")]
        public string Requests { get; set; }
        public Nullable<int> Status { get; set; }
        [Display(Name = "Ngày đặt phòng")]
        [Required(ErrorMessage = "Không được để trống")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> BookingDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RevervationRoomType RevervationRoomType { get; set; }
        [Display(Name = "Phòng")]
        public virtual ICollection<ReservationsRoom> ReservationsRooms { get; set; }
    }
}
