//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Room
    {
        public Room()
        {
            this.ListRooms = new HashSet<ListRoom>();
            this.ReservationsRooms = new HashSet<ReservationsRoom>();
        }

        public string RoomNoID { get; set; }
        [Display(Name = "Tầng")]
        public Nullable<int> Floor { get; set; }
        [Display(Name = "Phòng")]
        public Nullable<int> Position { get; set; }

        public string RoomTypeID { get; set; }

        public Nullable<int> RoomStatus { get; set; }
        [Display(Name = "Số điện thoại")]
        public string RoomPhone { get; set; }

        public virtual ICollection<ListRoom> ListRooms { get; set; }
        public virtual RoomType RoomType { get; set; }
        public virtual ICollection<ReservationsRoom> ReservationsRooms { get; set; }
    }
}
