//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UsersID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string NativeCountry { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<bool> systemRolle { get; set; }
        public Nullable<bool> resourceRolle { get; set; }
        public Nullable<bool> ReservationRolle { get; set; }
        public Nullable<bool> reportRolle { get; set; }
        public string Pass { get; set; }
        public string login_id { get; set; }
    }
}
